### ISSUE TITLE
привязка к кошельку

### ISSUE THREAD

**Issue by Savva350504** [Tarulis350504/Bitcoin-tracker-Ultimate-pro-v1.01-beta#1]
Интересное приложение с достаточно сложной реализацией. Возможно даже слишком сложной.  Я думаю что для полноты проекта не хватает привязки к электронному кошельку, потому как это первое, что может понадобится пользователям биткоинов. А вот какой практический смысл несёт подсчёт биткоинов в "реальном" обращении??? Это сложно делать а смысла 0...

**Comment by the-tarulis** [comment]
да.... сейчас посидел-подумал - рили как-то перемудрил, наверное... долго думал над этим алгоритмом подсчёта... хотел сделать это изюмом, но без всего остального это бессмысленно, а вместе со всем остальным - раздуто. скорее всего не буду его делать всё же

**Comment by the-tarulis** [comment]
а к кошельку не хочу привязывать, потому что не смогу протестировать....
нету у меня денег биткоины покупать....

**Comment by Savva350504** [comment]
привет

**Comment by Savva350504** [comment]
привет
